language: go
go: 
 - "1.11.x"

os: osx

install: true

addons:
  homebrew:
    packages:
    - lame

env:
  global:
    - GO111MODULE=on
    - CODECOV_TOKEN="fda83ffd-7216-4c61-a060-ed9cb8596f6e"

script: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)